server:
  port: 8081

spring:
  application:
    name: api-gateway

  main:
    web-application-type : reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: keycloak
          uri: http://localhost:8080/
          predicates:
            - Path=/keycloak/**
          filters:
            - RewritePath=/keycloak/(?<segment>.*), /$\{segment}

  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/keycloak/realms/dataq
        registration:
          keycloak-provider:
            provider: keycloak-provider
            client-id: api-gw-client
            scope:
              - openid
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'
